# Generated by Django 6.0.7 on 2026-07-13 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('type', models.CharField(max_length=100, verbose_name='Тип тура')),
                ('duration', models.CharField(max_length=100, verbose_name='Длительность')),
                ('duration_days', models.PositiveSmallIntegerField(verbose_name='Дней')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('price_note', models.CharField(blank=True, max_length=200, verbose_name='Примечание к цене')),
                ('image', models.URLField(max_length=500, verbose_name='Обложка')),
                ('video', models.CharField(blank=True, max_length=500, verbose_name='Видео превью')),
                ('alt', models.CharField(max_length=300, verbose_name='Alt-текст обложки')),
                ('gallery', models.JSONField(default=list, verbose_name='Галерея')),
                ('description', models.TextField(verbose_name='Описание')),
                ('highlights', models.JSONField(default=list, verbose_name='Особенности')),
                ('included', models.JSONField(default=list, verbose_name='Включено')),
                ('not_included', models.JSONField(default=list, verbose_name='Не включено')),
                ('difficulty', models.CharField(choices=[('Лёгкая', 'Лёгкая'), ('Средняя', 'Средняя'), ('Сложная', 'Сложная')], max_length=20, verbose_name='Сложность')),
                ('group_size', models.CharField(max_length=50, verbose_name='Размер группы')),
                ('season', models.CharField(max_length=100, verbose_name='Сезон')),
                ('location', models.CharField(max_length=200, verbose_name='Локация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('images', models.JSONField(default=list, verbose_name='Фото')),
                ('video', models.CharField(blank=True, max_length=500, verbose_name='Видео')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='api.tour', verbose_name='Связанный тур')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_slug', models.CharField(max_length=100, verbose_name='Слаг тура')),
                ('date', models.DateField(verbose_name='Дата начала')),
                ('guests', models.PositiveSmallIntegerField(default=1, verbose_name='Гостей')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Заявка на бронирование',
                'verbose_name_plural': 'Заявки на бронирование',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(verbose_name='День')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='api.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'День маршрута',
                'verbose_name_plural': 'Дни маршрута',
                'ordering': ['day'],
                'unique_together': {('tour', 'day')},
            },
        ),
    ]
